HIGH_PD = "HIGH_PROBABILITY_OF_DEFAULT"

HIGH_LTI = "HIGH_LOAN_TO_INCOME_RATIO"

HIGH_BNPL_BURDEN = "HIGH_BNPL_PAYMENT_BURDEN"

NEGATIVE_BALANCE_ACTIVITY = (
    "FREQUENT_NEGATIVE_BALANCE_ACTIVITY"
)

LOW_DATA_CONFIDENCE = (
    "INSUFFICIENT_BANK_DATA_CONFIDENCE"
)

BANK_DATA_UNAVAILABLE = (
    "BANK_DATA_UNAVAILABLE"
)

LOW_AND_GROW = (
    "LIMITED_INITIAL_EXPOSURE"
)

APPROVED = "POLICY_REQUIREMENTS_MET"

NEGATIVE_EXPECTED_PROFIT = "NEGATIVE_EXPECTED_PROFIT"